### ISSUE TITLE
Miniconda download location changed

### ISSUE THREAD

**Issue by j-wags** [MolSSI/cookiecutter-cms#103]
The download page for miniconda changed from https://repo.continuum.io/miniconda/  to https://repo.anaconda.com/miniconda/

This breaks the miniconda installation in `before_install.sh`.

The following line will need to be updated in all cookiecutter-based repos: https://github.com/MolSSI/cookiecutter-cms/blob/1a67980182f41598b29acf00d26909b77fd29d83/%7B%7Bcookiecutter.repo_name%7D%7D/devtools/travis-ci/before_install.sh#L18

Two current options are:
* Changing the URL directly
* Changing from `curl -s` --> `wget -qO-`

**Comment by j-wags** [comment]
I'm in favor of applying both changes. The URL change removes our reliance on the continuum.io --> anaconda.com redirect, and the `curl` --> `wget` change seems to change our default behavior to be "follow redirects" (though I'm not expert in curl vs. wget behavior)

**Comment by Lnaden** [comment]
We can actually get redirect follows in =`curl` with `-L` flag as well.

**Comment by Lnaden** [comment]
Either way, we have to change something since that website has apparently been moved to a new location and the `.io` is now a redirect.

**Comment by j-wags** [comment]
Can we find any official word on the URL change? This seems to be just a few hours old, so I don't have a sense for whether this is a permanent change or not.

**Comment by loriab** [comment]
I have a mild preference for the `wget` since now same cmd used for both the file and the md5.

**Comment by mattwthompson** [comment]
> Can we find any official word on the URL change? 

Can't find anything on twitter, their website, or the common issue trackers

**Comment by loriab** [comment]
posting what the error looks like so google searches can find this

```
-- Installing latest Miniconda
-- Miniconda latest version NOT FOUND in cache
Miniconda MD5 mismatch
```
