### ISSUE TITLE
default.profraw file generated

### ISSUE THREAD

**Issue by mattwthompson** [MolSSI/cookiecutter-cms#105]
```
$ conda create -n mars python=3.8 cookiecutter -c conda-forge
...
$ cookiecutter gh:molssi/cookiecutter-cms
...
$ # Do a normal cookiecutter setup
$ cd mars
$ ls *profraw
default.profraw

```

Do we want this file to be included by default?

I didn't find anything in the cookiecutter repo about this. It may only be generated on Python 3.8?

**Comment by mattwthompson** [comment]
I have no idea what this file really does; @j-wags suggested we could just add this extension to the ignore

**Comment by mattwthompson** [comment]
This may be specific to macOS; I don't get it on Ubuntu 20.04. From some googling, this seems to be a file format used by LLVM for code coverage. Anybody's guess here is as good as mine ...

**Comment by janash** [comment]
I am not able to replicate this problem on my laptop (macOS Catalina 10.15.4) in a Python 3.8 environment. I have never heard of this file before, so I have no guess as to why you are seeing it. 

Is this file committed in the initial CookieCutter commit, or does it show as an untracked file after running CookieCutter?

**Comment by mattwthompson** [comment]
Thanks for looking into this. Last month, it showed up immediately after running cookiecutter, before committing. I think we (at least @dgasmith and I, possibly others) noticed in when it showed up in the `git status`. I poked around the cookiecutter issue tracker and didn't get anything. If attendees at other workshops haven't noticed the file, maybe it wasn't being generated too often?

I just tried to replicate it in a new directory and environment and it did not show up. I am also running 10.15.4 now, but was on Mojave when I opened this issue. I will close this for now, although if it pops up again somebody can re-open.

**Comment by RMeli** [comment]
@mattwthompson For the records, I've recently got `default.profraw` files popping up as well on macOS.

**Comment by mattwthompson** [comment]
Strange - Catalina or Mojave?

**Comment by RMeli** [comment]
Catalina. I think it was version 10.15.4 and with Python 3.7. I know of other people noticing this too.

**Comment by Lnaden** [comment]
This is something I can test locally sometime this week. Its not too hard to do a `try...except` cleanup on this.

For those of you seeing this, can you get the exact OS, Python, and options you selected for it so we can replicate this best we can?

**Comment by WG150** [comment]
> I have no idea what this file really does; @j-wags suggested we could just add this extension to the ignore

I've had this issue in the past with a random `default.profraw` file in my local repos. I tend to just add it to my `.gitignore` but I've no idea why it crops up. 

- OS: macOS Catalina (10.15.5)
- Python 3.6.10

**Comment by janash** [comment]
Yes, the reason I asked previously if it was in the initial cookiecutter commit or if it is something that shows up as a new file in `git status` is because it gives us a clue about how and when the file was generated. 

If it shows up as a new file in `git status`, it is generated sometime after the initial cookiecutter commit and is being added by some reason by your operating system or something on your computer. Cookiecutter generates files once and all of those are in the initial commit.  However, if multiple people are seeing it on Mac, we can add it to `.gitignore`. I think it's appearing for reasons unrelated to cookiecutter, however.
