### ISSUE TITLE
Allow easy readthedocs integration

### ISSUE THREAD

**Issue by xiki-tempula** [MolSSI/cookiecutter-cms#114]
readthedocs allows free hosting of the doc and is using sphinx as the backend. I think it will be very helpful if relevant yaml files could be setup by the cookie cutter.

**Comment by janash** [comment]
I was working on this a while ago (#93 ). I can try returning to it soon to see if what I had in this PR can be brought up to date.

**Comment by dgasmith** [comment]
As a quick note I have switch to [MkDocs Material](https://squidfunk.github.io/mkdocs-material/) + Netlify these days. No ads and I find it a bit easier experience since its pure Markdown + pure JAMStack without the majority of Sphinx's idiosyncrasies. 

Worth noting there is also a [Sphinx Material](https://bashtage.github.io/sphinx-material/) if you like the look.

**Comment by janash** [comment]
Excellent to know! I am getting my PR on RTD up to date, but I imagine this might warrant some discussion on what to include.  Material looks like a very nice Sphinx theme. I imagine this could also be used with RTD. So MkDocs is another documentation tool besides Sphinx?

We could give people the choice of docs tools (MkDocs or Sphinx), but this would (I imagine) require someone to develop the MkDocs files. We could also give a choice on Sphinx theme (Material vs RTD), or even change the default theme of the cookie cutter. Many choices!

I'm finishing up the PR for supporting RTD hosting with Sphinx, just in case we want to support that for now.

@Lnaden , thoughts?

**Comment by loriab** [comment]
> As a quick note I have switch to MkDocs Material + Netlify these days.

Aha, I've been wondering what pydantic was using.

**Comment by dgasmith** [comment]
Sphinx RTD is a good default, its likely the most widely used in this space and while finicky- resources on how to work around Sphinx/RTD issues are well known. MkDocs Material is newer (as seen by the syntax and code style), but also means the module ecosystem and support network are less robust. I'm not sure I suggest supporting too many options here, but I hope worth being aware of!

**Comment by dgasmith** [comment]
> > As a quick note I have switch to MkDocs Material + Netlify these days.
> 
> Aha, I've been wondering what pydantic was using.

I also think Pydantic's auto doc generation is 🔥. Automatically builds the example [here](https://pydantic-docs.helpmanual.io) from a python file without comments.

**Comment by janash** [comment]
Closed by #115 . This PR added a RTD yaml and a conda environment yaml in the docs folder.
