### ISSUE TITLE
main - master

### ISSUE THREAD

**Issue by t-kimber** [MolSSI/cookiecutter-cms#120]
This cookiecutter template is great! 

However, I had a few issues working with it recently due to the GH changes from  _master_ to _main_. Should the template be changed accordingly ?

**Comment by Lnaden** [comment]
Can you be more exact on what the issues were for it? This is something I have been watching for, but have not seen what the explicit error is.

**Comment by t-kimber** [comment]
The GH actions were not running until I changed master to main in the workflow yaml file.

**Comment by Lnaden** [comment]
Odd. They work fine here. I'm assuming its this repo where you are seeing the problem https://github.com/t-kimber/maxsmi ?  I see that the new repo has its initial branch called "main" whereas existing repos still have the "master" designation. I can fix this, but I think we have to have both for legacy and new repos.
