### ISSUE TITLE
Drop Support for Travis and Appveyor - Discussion

### ISSUE THREAD

**Issue by Lnaden** [MolSSI/cookiecutter-cms#122]
Question: Should we drop support for Travis and AppVeyor and exclusively go with GitHub Actions?

Pros of switching CI: 
* GHA has native integrated support for Linux, OSX, and Windows. 
* GHA has a much more robust and easier to understand (and documented in many cases) YAML syntax and execution order. 
* Azure seems to be the system Conda-Forge has been slowly migrating to (what the backend GitHub Actions runs on as i understand)
* Has the backing of GitHub itself, so likely not going anywhere.
* AppVeyor is slow to run its tasks and update its images. 
* Any attempt to publish Conda Forge packages on the platform (which is fading out, but many accounts are still linked) takes ages to populate the list. 
* Travis has been steadily getting worse in terms of execution time (#121 took 3+ hours to run, through the Linux platforms!)
* The shuffling of the `.org` to the `.com` domain has caused many confusions, especially when integrating legacy codes which used the old Webhooks system instead of the new marketplace system.

Cons of switching to CI:
* Yet another CI system to learn with much fewer examples in the wild to pull from.
* More complex YAML file
* Still gaining features which others might miss
* Some personal anecdotal evidence of it being harder to do code compiles on and less compiler rich than Travis or AppVeyor
* Harder to test and maintain at the top-level cookiecutter

To any of our users, please let us know what your thoughts are.

@janash @dgasmith @jchodera @jaimergp

**Comment by dgasmith** [comment]
GHA CI has the incredible plus of the GitHub Action plugin framework:
- Conda install not working? Thats fine, bump the action version.
- No compilers? No problem either pull in a plugin that sets it up for you or start from a LLVM-toolchain image from DockerHub.
- No plugin for black linting? Use a python pip action to install black and validate in *5 seconds flat*.

Travis was bought out by Idera and the entire CI project was placed in limbo (see .org/.com pro/free issues). I do not believe its a maintainable framework.

**Comment by janash** [comment]
GHA is becoming more popular and will probably be what most people use going forward. If we do choose to drop, I think we could fade support/add some deprecation warnings before removing it completely. Perhaps we would want to pick a date/version where we plan to drop support.

If we choose to drop Travis/Appveyor we will likely be getting a lot of questions from people who have used older versions of the cookiecuttter on whether they should switch their CI/how they can switch. We should be prepared for those.

**Comment by jchodera** [comment]
+1 for going all-GHA

**Comment by jaimergp** [comment]
> If we choose to drop Travis/Appveyor we will likely be getting a lot of questions from people who have used older versions of the cookiecuttter on whether they should switch their CI/how they can switch.

Updating the cookiecutter template version is still a work in progress, right? Or is there any recommended procedure?

I don't think any _new_ users are interested in Travis unless they want native `ppc64le` CI, but that's such a corner case. I'm all in for a GHA exclusive set up, given the adequate deprecation warnings are added one version before the removal.

**Comment by Lnaden** [comment]
The comments all seem to be Pro-GHA only

> No compilers? No problem either pull in a plugin that sets it up for you or start from a LLVM-toolchain image from DockerHub.

I did not know that was an option, reduces my concerns from my anecdotal comment

>  If we do choose to drop, I think we could fade support/add some deprecation warnings before removing it completely. Perhaps we would want to pick a date/version where we plan to drop support.

I think this is a good idea, and the right way to go.

> If we choose to drop Travis/Appveyor we will likely be getting a lot of questions from people who have used older versions of the cookiecuttter on whether they should switch their CI/how they can switch. We should be prepared for those.

> Updating the cookiecutter template version is still a work in progress, right? Or is there any recommended procedure?

Both of these are valid points. We don't have a way to actually update the cookiecutter template, especially on a live version of the code. This is something we had thought about doing early on, but realized this would be virtually impossible to track once someone has implemented their own code, CI, and docs post-generation. Conda-Forge can get away with it because the bot is updating a file which must adhere to schema (`meta.yaml`), and several "user is explicitly told not to touch ever and we'll call you on it" folders and files. This is much harder to do in live code which may have deviated significantly. 

I do think we can find a middle ground and document and upgrade procedure with detailed steps and things to check before migrating. I can come up with some crude scripts which try to convert Travis/AppVeyor files into GHA files. They will likely not work in 20-30% of the cases, but it would give people an idea.

**Comment by dgasmith** [comment]
Travis updates: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

We should consider hastening this transition to GHA.

**Comment by j-wags** [comment]
A bit of a security vulnerability was recently disclosed in GH Actions [1]. It looks like best practices may have shifted to blanket anything involving echo'ing untrusted data into blocks bounded by `::stop-command` [2]. I doubt many people using the cookiecutter are doing anything this fancy, but this could be a good single place in the community to put it in so we don't risk leaking secrets.

[1] https://bugs.chromium.org/p/project-zero/issues/detail?id=2070&can=2&q=&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Summary&cells=ids
[2] https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by dgasmith** [comment]
Sounds like Travis CI will completely shut down for OSS: https://news.ycombinator.com/item?id=25338983

Looks a little unsubstantiated at the moment, but unsurprising.

**Comment by dgasmith** [comment]
I believe this issue was closed by #124.
