### ISSUE TITLE
C/C++ project integrations.

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/cookiecutter-cms#16]
This cookie cutter is great for pure Python projects, but a concern we will likely run into is how to integrate hybrid Python/C/C++ projects. Perhaps not recommended for this cookie cutter (we might consider another cookie cutter), but I think a reasonable place to open discussions.

Personally I try to adhere to the following rules:
 - If pure C, use Python `ctypes` and the wonderful [`numpy.ctypeslib`](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.ctypeslib.html).
 - If C++, use [PyBind11](https://github.com/pybind/pybind11). Note that mixing PyBind11 versions can be problematic.
 - If only called via Python try to use the native distutils/setuptools compilation options which work ok as long as nothing complex is used. This fails when binding complex C++/CMake ecosystems however (Psi4 as an example)
 - If called via Python and also linked at the shared object level write a `setup.py` that calls CMake. Example [here](https://github.com/dgasmith/gau2grid).

We have a number of solutions depending on the requirements and things get quite messy depending if CMake is in the mix or not. I have tried to follow [scikit-build](https://github.com/scikit-build) without too much success. Opinions and discussion are most welcome.

**Comment by Lnaden** [comment]
I think its a great idea to include this info! I don't think anyone has tried to tackle this yet in cookiecutter form.

Depending on how complex we make it, we could add a `cookiecutter.json` boolean/dict to include `C`/`C++` bindings and have Jinja add all the additional settings. Otherwise I think a derivative cookiecutter should be made.

I think we will need to be careful (or complex) with our Jinja templates depending on how complex we want to make a single repo.

> Personally I try to adhere to the following rules...

I like these rules, but I worry about how much we want to include with with a general repo for complex CMake builds. I think starting with those 4 points in a simple fashion may be a good starting point.

**Comment by dgasmith** [comment]
Most of the choices are not terribly complex to setup and can be handled by Jinja I believe. Mostly the diversity of options make the correct choice quite difficult. I do not have simpler rules of the thumb and I think will mostly come down to how everyone uses compiled languages (worth thinking about Fortran as well). 

In your experience is the largest user base:
A) Simple C programs to improve various loops (can be replaced by numba/numexpr?)
B) Relatively simple C++ programs to handle object-based loops or similar.
C) Complex C++ ecosystems such as RDKit integration or similar.

**Comment by Lnaden** [comment]
My personal experience is A and B in about equal proportions where users have somewhat simple C/C++ objects, but others may have different experiences. I would include `Cython` in the list of simple handlers too.

I think the audience falling in option C) category are probably not the target audience for this repo, unless you see people wanting to cross over from having complex C++ projects into the Python realm

**Comment by dgasmith** [comment]
Good point about `cython`, the toolchain should be pretty similar to A. For B we could perhaps simply say start with this cookie cutter and then follow the PyBind11 documentation which is fairly decent these days. I dont think we need to cookie cutter everything (especially if folks are at the level to bind C++), but simply pointing towards the desired way of performing these operations could be useful.

The C) option may natively class themselves out of cookie cutters to be honest.

**Comment by Lnaden** [comment]
> simply pointing towards the desired way of performing these operations could be useful.

That is probably a good idea. We can include that information here and maybe even provide simple instructions of how to modify this cookiecutter output to get started including the PyBind11 hooks.

**Comment by dgasmith** [comment]
The [gau2grid](https://github.com/dgasmith/gau2grid) repo has some CMake integration functionality. Not entirely sure if thats the ultimate way to go.

Another approach is [scikit-build](https://scikit-build.readthedocs.io/en/latest/) which is maturing, documentation and cognitive overhead seems to be improving well over time. Last time I checked I couldn't figure out a basic example.

**Comment by dgasmith** [comment]
Closing this, I think it falls outside of the scope of the project currently.
