### ISSUE TITLE
Remove default channel from conda-forge setting

### ISSUE THREAD

**Issue by Lnaden** [MolSSI/cookiecutter-cms#160]
Follow up to #159 

The `defaults` channel should be removed when using `conda-forge`.

This effects a couple places in the code:

* The CI setting in the `provision-with-micromamba`
* The primary Cookiecutter JSON file
* The Jinja templates in the CI file which use the Cookiecutter options to do `if..elif..else` statements.
* The README and docs

**Comment by janash** [comment]
@sjayellis - can this be closed after review23 was merged?

**Comment by sjayellis** [comment]
Yes, this can be closed now.
