### ISSUE TITLE
cruft remains in setup.cfg 

### ISSUE THREAD

**Issue by eirrgang** [MolSSI/cookiecutter-cms#161]
Commit https://github.com/MolSSI/cookiecutter-cms/pull/152/commits/800f4926e65f1883a996f344ac5eced7f2723e96 got partially reverted somewhere in the merge history, and now duplicates project metadata and setuptools configs that were supposed to be moved to pyproject.toml.

**Comment by janash** [comment]
@eirrgang - are you referring to lines `7-60` in `setup.cfg`? I see that (all?) of that info is also in `pyproject.toml`.

https://github.com/MolSSI/cookiecutter-cms/blob/main/%7B%7Bcookiecutter.repo_name%7D%7D/setup.cfg#L7

**Comment by eirrgang** [comment]
> @eirrgang - are you referring to lines `7-60` in `setup.cfg`? I see that (all?) of that info is also in `pyproject.toml`.
> 
> https://github.com/MolSSI/cookiecutter-cms/blob/main/%7B%7Bcookiecutter.repo_name%7D%7D/setup.cfg#L7

Exactly. Originally, commit 800f492 moved that stuff (with syntax updates) from setup.cfg to pyproject.toml, but somehow it got muddled in subsequent merges, and both were retained.
