### ISSUE TITLE
`provision-with-micromamba` is deprecated

### ISSUE THREAD

**Issue by mattwthompson** [MolSSI/cookiecutter-cms#171]
See https://github.com/mamba-org/provision-with-micromamba/pull/122 and its near-identical replacement https://github.com/mamba-org/setup-micromamba.

There does not appear to be urgency to _remove_ it and I speculate it might continue to work for a few years for most use cases.

So far, a couple of one-liners seem to be doing the trick within OpenFF infrastructure, which does not dig deeply into the options either action provides. Something similar might work in this repo, I have not tried it.

```shell
$ sed -i 's/provision-with-micromamba\@main/setup-micromamba@v1/g' .github/workflows/*
$ sed -i 's/extra-specs: |/create-args: >-/' .github/workflows/*

**Comment by janash** [comment]
Should be closed by #172 once `review23` in merged - @sjayellis can you confirm?

**Comment by sjayellis** [comment]
Yes, this should be taken care of once 'review23' is merged.

**Comment by janash** [comment]
I believe this can be closed now. Reopen if not the case :)
