### ISSUE TITLE
Add Contributor License Agreement and its hooks

### ISSUE THREAD

**Issue by Lnaden** [MolSSI/cookiecutter-cms#24]
What are people's opinions on adding a CLA to both the cookiecutter repo and the output project?

**Comment by dgasmith** [comment]
It could be an option, but they can get really tricky to setup. Do you have a suggested way of building these?

**Comment by Lnaden** [comment]
Not off the top of my head. I have also not looked into setting one up myself, but I wanted to at least pose the question to see if others had ideas.

**Comment by jchodera** [comment]
> What are people's opinions on adding a CLA to both the cookiecutter repo and the output project?

It's worth a try! Ideally, we'd have both (1) a CLA for contributions to the repo, and (2) the option to choose a CLA for contributions to the project being set up.

**Comment by dgasmith** [comment]
Several current options:
 - https://cla-assistant.io
 - https://github.com/apps/cla-bot

@j-wags

**Comment by dgasmith** [comment]
I think it might be wise to remove this issue from the cookiecutter. Something like this is good for organizations that have made this decision, but it is not clear there is a long-term stable solution and if it is worth the overhead for a new user to look at.
