### ISSUE TITLE
Double check the Versioneer docs

### ISSUE THREAD

**Issue by Lnaden** [MolSSI/cookiecutter-cms#53]
We should consider if we should make a note about the versioneer description to note that it is not really updated, but does still just work. Also double check the LGTM issue (#52) and Flake to ensure the Versioneer files are correctly ignored.

Possible alternate in the future: https://github.com/pypa/setuptools_scm/ (a la @dgasmith)

Notes of when Versioneer *might* fail in the future:
* Python drops the C-style string formatting (e.g. `"%d" % 10`). No noted plans to do so at the moment.
* `git` changes the syntax which Versioneer reads. Very unlikely for the foreseeable future
* `setuptools` changes the way it accepts additional modules. No sense of the likelihood of this.

**Comment by loriab** [comment]
I like the look-ahead scheme of setuptools_scm, but switching out seems very low priority. Keeping this open probably provides all the warning a user needs. Though they could be encouraged to always explicitly do zero-patch (e.g., `v1.2.0`) to be ready for the new tool.

**Comment by mattwthompson** [comment]
Another option for a possible post-versioneer future: https://github.com/c4urself/bump2version

**Comment by Lnaden** [comment]
This is superseded by #151.
