### ISSUE TITLE
"-" available to use in cookiecutter even though it is not valid for python

### ISSUE THREAD

**Issue by ocmadin** [MolSSI/cookiecutter-cms#61]
While going through the setup with `cookiecutter-cms` it gives me the option to name my project with dashes (e.x. `new-project`), but projects named with dashes are invalid for python.  Other users in the future may run into this issue.

**Comment by dgasmith** [comment]
Doesn't look like we can actually capture that correctly on first pass. We could add more comments there saying something like spaces/hyphens/etc are not valid Python.
