### ISSUE TITLE
Default Linux Travis py3.7 build for cookiecutter-derived repo fails

### ISSUE THREAD

**Issue by j-wags** [MolSSI/cookiecutter-cms#62]
Example of cookiecutter-derived package travis build failing: https://travis-ci.org/MSchauperl/resppol/jobs/477670412

Official announcement seems to say: "Move to xenial dist" https://travis-ci.community/t/unable-to-download-python-3-7-archive-on-travis-ci/639/2?u=kacperduras

Same issue was found and solved here: https://github.com/mediascopegroup/light-rest-client/issues/2

I was able implement the above solution for openforcefield by adding the `sudo: required` `dist: xenial` keywords. https://github.com/openforcefield/openforcefield/commit/47f74e82edec56bd03b8a047d320e15dc28382e2#diff-354f30a63fb0907d4ad57269548329e3

**Comment by dgasmith** [comment]
Strange that we have to pin `xenial` as it should be the default. Ah well, I guess if sudo is required they might have different defaults due to the fact `xenial` isn't a full container yet?

Let me look into this a bit before making changes.

**Comment by dgasmith** [comment]
So we pinned `resppol` to xenial to make everything work. Still not why that was needed. In general best not to pin `sudo` access unless required.
