### ISSUE TITLE
in conf.py, cookiecutter.description should be cookiecutter.project_name

### ISSUE THREAD

**Issue by j-wags** [MolSSI/cookiecutter-cms#64]
In [`docs/conf.py`](https://github.com/MolSSI/cookiecutter-cms/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/docs/conf.py#L22)

Per [Sphinx's documentation](http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-project), this should be the project name, not long description. Suggest changing to `cookiecutter.project_name`.

[Example of user overriding this behavior](https://github.com/openforcefield/propertyestimator/pull/8/files#diff-85987f48f1258d9ee486e3191495582dR22)

**Comment by dgasmith** [comment]
Agreed, can you fix?
