### ISSUE TITLE
Recommend numpy docstring standard by default?

### ISSUE THREAD

**Issue by jchodera** [MolSSI/cookiecutter-cms#68]
Currently, the [sphinx extensions](https://github.com/MolSSI/cookiecutter-cms/blob/master/docs/conf.py#L41-L43) do not include [`numpydoc`](https://numpydoc.readthedocs.io/en/latest/) to render numpy style docstrings, which are both human- and sphinx-readable.

What do folks think about including `numpydoc` by default and encouraging users to follow the numpy docstring convention?

**Comment by dgasmith** [comment]
NumPy-style docs would be my preferred way of doing things over Google-style by far. We usually route through Napoleon over numpydoc however.

It would be good to take a wholistic approach to the default addons as there are several very useful ones like intersphinx and autosummary as well.

**Comment by loriab** [comment]
+1 for numpy-style docstrings.

looks like psi is using napoleon and some astropy-originated tools for auto-api. https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/conf.py.in#L74-L83

+1 for intersphinx, too

**Comment by j-wags** [comment]
+1 for napoleon. I really like the look of it, and once I've had a chance to play with it on my own repos, I think it would be good to push it to the other OpenFF projects too. 

There's a parallel conversation about it here: https://github.com/openforcefield/propertyestimator/pull/13
