### ISSUE TITLE
Conda Codecov

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/cookiecutter-cms#77]
Apparently codecov is on conda-forge and I missed it. Looking at the time stamps I think I started using codecov over two years ago and never checked again!

It would be good to leave pip stubs commented out in the conda env for demonstration however.

**Comment by dgasmith** [comment]
@janash Did you want to tackle this or should I update it?

**Comment by janash** [comment]
Whoops, I looked at this a while ago and forgot to submit a PR. It's just changing `codecov` to be under `dependencies` instead of `pip only installs` in `test_env`, right?

**Comment by dgasmith** [comment]
Yes, but only for c-f channels. Conda base does not have it.

**Comment by janash** [comment]
okay, I'll have to look at this a little later today

**Comment by dgasmith** [comment]
Closed by #80.
