### ISSUE TITLE
Automating package and data discovery 

### ISSUE THREAD

**Issue by jaimergp** [MolSSI/cookiecutter-cms#78]
Hello :)

Is there any reason the template recommends manually specifying packages and subpackages instead of using  `setuptools.find_packages()`? 

Also, [some people](https://blog.ionelmc.ro/presentations/packaging/#slide:15) recommend against using `package_data`, suggesting `include_package_data=True` and `MANIFEST.in` as a cleaner replacement.

Would you consider changing the current behavior?

**Comment by dgasmith** [comment]
Very much on board with `setuptools.find_packages()`, I change it myself and not totally sure why it is in its current state.

For MANIFEST I worry a bit that this creates additional complexity as users have to find another file to add their source too. At the same time without the MANIFEST some not-often used ways of deploying packages hits some issues with versioneer. Does anyone else have strong preferences here?

**Comment by jaimergp** [comment]
That author, Ionel Cristian Mărieș, has some [[1](https://blog.ionelmc.ro/2014/05/25/python-packaging/), [2](https://blog.ionelmc.ro/2014/06/25/python-packaging-pitfalls/#forgetting-package-data)]. In the slide 16, he suggests using a general `MANIFEST.in`:

> Just take whatever you have on the filesystem:
> [MANIFEST.in]
>     graft mypackage
>     global-exclude *.py[cod] __pycache__ *.so

That way, all non-Python files within the package are included. If there are files that shouldn't be included in the final distribution then they should not be stored within the package anyway.

While the posts are 5 years old, I think they add some value to the discussion. 

_Offtopic_
He also has some strong points about the package structure (using `src/<mypackage>` instead of `<mypackage>`), although he _recently_ wrote [a new post](https://blog.ionelmc.ro/2017/09/25/rehashing-the-src-layout/) where he revisits the idea.

**Comment by dgasmith** [comment]
Re `src`: In general, we view the [NUMFOCUS](https://numfocus.org) and anaconda style projects as the de facto standard in the organization and best practices (where applicable) within the python-based science community. So we would likely push back fairly heavily against that one.

Do you have other authors that argue one way or another? Ionel seems to steer more into the general web framework domain which is quite different from our current  practices.

**Comment by Lnaden** [comment]
Im okay with the `find_packages` function, go for it!

I go back and forth on the MANIFEST.in vs setting manually. I think moving towards the MANIFEST.in is the correct answer though the more I have considered. Mainly because the MANIFEST.in + `include_package_data=True` since that will work with both source and binary distributions, where as the `pacakge_data` is only really for source dists. So I think moving forward with that is a good idea.

I do hold the same stance as @dgasmith on the `src/...` folder structure and at the moment would reject it outright.

When we originally wrote the cookiecutter, it was meant as both a quick get-up-and-go project, and as an educational tool for learning how the python setup and package building should work and be done. As its evolved over time, I think the former is showing more dominance, but I would like to keep everything well documented and clear for those who want to dig in. So, sure, go for it!

**Comment by Lnaden** [comment]
There was some oddities in the pre-py2.7 days about how MANIFEST.in was considered or not, but since Python 2.7 (and especially Python 3 since that is all this cookiecutter really supports), its much more uniform and consistent, so long as you set the `include_package_data` and are using `setuptools`

**Comment by jaimergp** [comment]
I looked for `Manifest in python best practices` in Google, and visited the all websites in the first page. Some highlights:


## [`packaging.python.org`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#manifest-in)
> A MANIFEST.in is needed when you need to package additional files that are not automatically included in a source distribution. [...] For an example, see the MANIFEST.in from the PyPA sample project.

This example file:
```
# Include the README
include *.md

# Include the license file
include LICENSE.txt

# Include the data files
recursive-include data *
```
Then, in [`setup.py`](https://github.com/pypa/sampleproject/blob/master/setup.py#L167-L171) they use `package_data` anyway. ¯\_(ツ)_/¯

## [`the-hitchhikers-guide-to-packaging.readthedocs.io`](https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/creation.html)

> The MANIFEST.in file should contain this:
> ```
> include *.txt
> recursive-include docs *.txt
> ```

## [`alexanderwaldin.github.io`](http://alexanderwaldin.github.io/packaging-python-project.html)

> Now that we've written the setup.py script, let's take a look at writing the MANIFEST.in file.
> 
> ```recursive-include projectname *.py
> recursive-include projectname *.pickle
> include README
> include LICENSE
> include requirements.txt
> ```
> The manifest is used to specify files to include in the distribution that are not mentioned in the setup.py script. Usually these are files like unittests, the README file, the requirements.txt file etc. Specify which files to include using Unix-style "glob" patterns.
> 
> Check-Manifest
> Often it can be tricky to make sure that everything that needs to be included in the source distribution is actually getting included. A wonderful tool to help you is check-manifest, check-manifest verifies that everything that's under source control is being included in the distribution, and if something is missing, it will offer suggestions as to how you should modify your MANIFEST.in file. 


I agree that this introduces more complexity, but that's why we are using templates in the first place. Then, we have the whole thing about [PEP 518](https://www.python.org/dev/peps/pep-0518/), Poetry and `pyproject.toml` as the definitive answer... :man_facepalming: 

Obligatory XKCD:

[![standards](https://imgs.xkcd.com/comics/standards.png)](https://xkcd.com/927/)

**Comment by Lnaden** [comment]
I think the answer here is to switch to `MANIFEST.in` + `include_package_data=True` to ensure its always captured, even in zip safe mode and for {x}dists, which should cover development, pypi, and conda-based installs. 

I also think moving to the `find_packages` is fine. 

> Then, we have the whole thing about PEP 518, Poetry and pyproject.toml as the definitive answer... 

I think we can safely punt on those for now and address those later down the road if people want to start including those.

**Comment by jaimergp** [comment]
Perfect! I 100% agree. May I submit a PR? Any contribution guidelines I need to read before that?

**Comment by Lnaden** [comment]
> May I submit a PR?

Absolutely!

> Any contribution guidelines I need to read before that?

Not on this one, just a fork and PR should be fine

**Comment by dgasmith** [comment]
@jaimergp I think this is good to close now that #79 is in?
