### ISSUE TITLE
Using more providers: Azure Pipelines / GitHub Actions

### ISSUE THREAD

**Issue by jaimergp** [MolSSI/cookiecutter-cms#90]
I have been testing Azure Pipelines while trying to build `openmm` in `conda-forge` and I have really liked the UI and the added consistency due to the fact that all OS run on the same platform. Will you consider migrating from Travis/AppVeyor to an unified Azure CI?

**Comment by dgasmith** [comment]
We keep toying around with this. Azure has come a *very* long way in the past year in terms of user friendliness, but Linux testing Travis CI is hard to beat in terms of simplicity. This cookiecutter is really targeted at users who are not familiar with CI which make it hard to recommend Azure services.

For example, if I wished to add another person to admin status on an Azure Pipeline I used to have to check ~30 boxes to grant them these permissions and they still do not have full access (sorry @Lnaden!). I haven't checked lately to see if they have made this easier.

That being said we use Azure very extensively in most of our projects and definitely recommend it for power users.

**Comment by jaimergp** [comment]
Hi again @dgasmith!

Now that GitHub Actions [has been publicly released](https://github.blog/2019-11-13-universe-day-one/), what about this provider? I have played a bit by adapting the Travis recipe, and works wonderfully. Check it here:

- [Example build](https://github.com/openkinome/kinoml/commit/86a58b5116c740a90ed94ff1050cc8f9b00cca57/checks?check_suite_id=286257541) - look at those build times!
- [Implementation](https://github.com/openkinome/kinoml/blob/master/.github/workflows/ci.yaml)

**Comment by dgasmith** [comment]
Pretty sure GitHub Actions leverage Azure devops as a backend which makes it super flexible while being sane on the front end. I am very much in favor of rewriting the current CI to GitHub actions.

@Lnaden @janash

**Comment by dgasmith** [comment]
@jaimergp After chatting with the team we are in :) Please make a PR!

**Comment by dgasmith** [comment]
Also see [here](https://github.com/psi4/psi4/blob/master/.azure-pipelines/azure-pipelines-linux.yml#L74) to end env variables on every script init.

**Comment by jaimergp** [comment]
Added to my list! I'll try to put something together as soon as possible!

**Comment by dgasmith** [comment]
Awesome, thanks for helping with this! Let us know if your plans run long, we may add something soon as we are quite enthused about this possibility.

**Comment by dgasmith** [comment]
Quick heads (which I suppose most know). `setup-miniconda` was moved to `Conda-incubator` by the conda-forge folks [here](https://github.com/conda-incubator/setup-miniconda).

It's pretty 🔥 , used it for a dozen repos in the past ~6 months. No issues, lightning fast, and they do caching right™.

GitHub Actions is snapper, parallelizes better, and is easier integrated with GitHub than travis/appveyor.

**Comment by jaimergp** [comment]
I think Matt submitted #113 for this!

**Comment by Lnaden** [comment]
This can be closed now that GitHub Actions are in.
