### ISSUE TITLE
devtools/scripts/create_conda_env.py does not report which channels packages are installed from

### ISSUE THREAD

**Issue by jchodera** [MolSSI/cookiecutter-cms#96]
We've been converting some of our legacy projects over to the CMS cookiecutter, but I've noticed that the new travis scheme can make debugging harder because the `devtools/scripts/create_conda_env.py` mechanism does not emit information on which channels each package is installed from. When tracking down issues where pulling a package from a different channel causes failures, this can be immensely valuable.

What would you think about one of these options?
1. Having `devtools/scripts/create_conda_env.py` generate a list of which channels each package version is coming from (the same way `conda install <packagename>` does), or
2. Adding a `conda list` to the `.travis.yml`?

**Comment by loriab** [comment]
`conda list --show-channel-urls` is invaluable, imo.

**Comment by dgasmith** [comment]
2) will satisfy 1) here?

A conda list was accidentally omitted. @jaimergp can you add this to the GHA switch over?

**Comment by jchodera** [comment]
Yes, (2) would work well!

**Comment by dgasmith** [comment]
Two items 1) `create_conda_env.py` is deprecated in favor of the more stable `setup-miniconda` action and 2) a Conda-list is emitted during the GHA step. Closing, but please reopen if needed.
